spring:
  application:
    name: spring-boot-ncs-evaluation
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    driverClassName: org.mariadb.jdbc.Driver
    username: test
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      encoding: utf-8
      locations:
        - classpath:db/data.sql
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        use-sql-comments: true
        default-batch-fetch-size: 500
  logging:
    level:
      '[lab.nomad.springbootncsevaluation]': DEBUG
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false