spring:
  application:
    name: spring-boot-ncs-evaluation
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      encoding: utf-8
      locations:
        - classpath:db/data.sql
  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        use-sql-comments: true
        default-batch-fetch-size: 500
  logging:
    level:
      '[lab.nomad.springbootncsevaluation]': DEBUG
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false